language: ruby
services:
  - postgresql
rvm:
 - 2.3.5
env:
 - db=postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: 9068ca9c-affd-4b78-81e6-4509c05df5e1
  app: dry-bastion-60075

# env:
#   global:
#     secure: IlesowXN6mWb2lZBYGvMVd+I8LNgZyMMwdO7T3tAnzThNxEflsCAc/1wPQI0P8eHhkdAVAhz84QHfxK3NjgBG/qkkyADJnBrAvocz36zuQ6xPDfLqj/okNuCnEOgvhUglJTyoMGmde5mblWKTbhBXbI1LI+Tqeh4a1f+lawRvG/wP7f0o+/Nx5WTKNzTy+H19L86RDBOzYgBjBHGWYqidAKkmwGlIljQBjD1YLiRefytfdR5w69Z+alkMFAVUscx+Ns+ojMYNdyX5aAfSzvUaRH0WNUPGOE35psQ0rEZ3A5/40C5+bGQ2p11A13Vewo7wAjG3Ux3Em7cZ9YsRR2xJzaQx52hyRBa8skHsbQdSBubUk4pF2gWsEL5gQDzBrj6rmc2R/v/pr+RmY4FBD9mfFJB3sqYmlFVKiYowj61WkUx79s+thOOZx0iqe7+wYQAIM0ZssIDGNKXEkFgYWRKjLgJQGwbyd38w63aSDPj/rpbj9QNE+XOqHdxozFIsxKqAmwwzd6hjPJmhtJYtIvnsJylTCgQUi4uQh34VfNuFlxRS4bCgDI1ZY70qKxmaXxuw2tS2CmaFVS3w1r7UEodxewVDwmXWYgAZbhaQPoG2spsgXkpgYfPYbE8JA5K9DOYItFwMXYkNA9rp3hwbIXzkFFY3P8jT01M6B0hvAid+aY=
